#%RAML 1.0
title: Books REST API
version: 1.0
baseUri: http://localhost:8080

type:
  Book:
    type: object
    properties:
      id:
        type: number
        readOnly: true
      title:
        type: string
      genre:
        type: string
      publicationYear:
        type: number
        required: false

/books:
  displayName: Books
  get:
    description: Listar todos los libros
    responses:
      200:
        body:
          application/json:
            type: array
            items: Book
  post:
    description: Add a new book
    body:
      application/json: Book
    responses:
      201:
        body:
          application/json: Book
  /{bookId}:
    get:
      description: Get information about a book
      responses:
        200:
          body:
            application/json: Book
        404:
          description: Book not found
    put:
      description: Update a book
      body:
        application/json: Book
      responses:
        200:
          body:
            application/json: Book
        404:
          description: Book not found
    delete:
      description: Delete a book
      responses:
        204:
